mt76: enable MAC80211_LEDS by default
Select mac80211 led support by default in order to fix the following
compilation error that occurs when CONFIG_LEDS_CLASS/CONFIG_MAC80211_LEDS
options are not enabled on the system

ERROR: "devm_of_led_classdev_register" undefined!

Fixes: 17f1de56df05 ("mt76: add common code shared between multiple chipsets")